### PR TITLE
Fix changes in ogame code

### PR DESCRIPTION
**Pull request by dr1s**
There apparently have been some changes to ogame code, as my bot wasn't able to get the amount of defenses and the level of research items.
This PR fixes it.

### CODE REVIEW

**Comment by winiciuscota** [comment]
My bot is working fine. Did you try to run the bot while there was defenses/research in progress?

**Comment by dr1s** [comment]
That could be it, I will look into it further.

**Comment by winiciuscota** [comment]
There is bug in which the bot crashes if you try to log the defenses/constructon while they are in progress.
Maybe you have fixed that

**Comment by dr1s** [comment]
IIRC there was some research and defense construction in progress. Right now i can not reproduce it.

**Comment by winiciuscota** [comment]
I just tried it, with the new code the bot isn't crashing when there is defenses in construction

**Comment by dr1s** [comment]
Glad it works for you, but there is still some bug in the research part. I actually just encountered it.
This also only happens if there is already research in progress...

**Pull request merged**
